#!/bin/bash
curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
apt-get install nodejs -y
git clone https://github.com/draco-labes/oversee-fixed.git && cd oversee-fixed && npm install && npm run seed && npm run createUser && node .
